# Generated by Django 2.2.16 on 2021-03-21 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mygroup',
            old_name='author',
            new_name='creator',
        ),
    ]
