# Generated by Django 2.2.16 on 2021-03-21 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20210321_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mygroup',
            name='creator',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
