# Generated by Django 2.2.16 on 2021-03-21 05:39

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20210321_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mygroup',
            name='creator',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
