# Generated by Django 3.1.6 on 2021-05-09 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_mygroupfiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyGroupFiles',
        ),
    ]
