# Generated by Django 2.2.16 on 2021-03-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210325_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='IV',
            field=models.TextField(default='qzTEjmoHyT'),
        ),
    ]
