# Generated by Django 2.2.16 on 2021-03-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20210325_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='IV',
            field=models.TextField(default='qvUPRdaeEF'),
        ),
    ]
