# Generated by Django 2.2.16 on 2021-03-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20210325_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ivk',
            name='IV',
        ),
        migrations.AddField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'\xe0\x8f\x0f\xc1\x1c\x8c?\x82\x1a\xeb\x906\x8b\x9f\x01H\x93\xb7W\xf6\x99M_\xc03\xd7P-\x12\xd5L\x1b'),
        ),
    ]
