# Generated by Django 2.2.16 on 2021-03-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20210325_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'@\xf4\xa9\x13{!\x82\xac\xb4\xaf-\xa9\x80\x0e\xcd9\x1eq\x92\x96\xd8\xbc-\x0cMDM\xdd>cM\x98'),
        ),
    ]
