# Generated by Django 2.2.16 on 2021-03-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20210325_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'\x80(I\xa4\xaaQ\x95\xd6\x0f\x8f\xc0T\x0c\xcd*\x96\xdb:\x07\x887}\xc9\x95\x85\x96\x8e\xf5(\x0e\x04%'),
        ),
    ]
