# Generated by Django 2.2.16 on 2021-03-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20210325_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'\xea\xc7R\xbe\x9bm \xe7\x8c\xc4\x93\x98\xdc4F"\x96\xaa\x88\xd0\xb1\xd4\xd6(B\xb9\xaf\xf0\x15\x07\x9dj'),
        ),
    ]
