# Generated by Django 2.2.16 on 2021-03-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20210325_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'C\xf32y\xf4n\x14\xfd\xbd\x175\x9b\\\xf1\xcd\xf8\x9d\xdd\x9e\xebUB\x1f\x10;\xa3\x1fJ\x01#\x11{'),
        ),
    ]
