# Generated by Django 2.2.16 on 2021-03-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20210325_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'^\xa2_\x85-\xb9XE.X\x8bjO\xf6\xec\xdf\x0eM%\xd6M8\xbfg^\x1c\xd9\x9e\xf6@\xf9\x91'),
        ),
    ]
