# Generated by Django 2.2.16 on 2021-03-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20210325_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'\x9d\xa3\xbb:\xb0\xd9\xe6\x16i\x9b\xe2\x12\xcb;O\x9c\x99\x86R\x97(\xffplk\xa2P\x96\xe0\x92\x1e\x1e'),
        ),
    ]
