# Generated by Django 2.2.16 on 2021-03-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20210325_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'\xf8\xa0|\xdd,\xa4YH\x19\xa6"\x14\x02k;\xdd\xe3,H\x1b\x94\x8e[m\xd7\xfb\xf0\xab\x96\xa0\xcf\x81'),
        ),
    ]
