# Generated by Django 2.2.16 on 2021-03-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20210325_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'\xbeB\xbeN\xba\xe0;P\x1c\xd5J\xfc\xe1E\xa5B\xe2K~\x013j\x8dw\xdf\x97\x13\xab\xbes\\v'),
        ),
    ]
