# Generated by Django 2.2.16 on 2021-03-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20210325_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'3\x02\xe7\xd1b\x97\x10.\x17 \xbf\xda\x94b\xf0\x92\x85?\x0e\xd0j\x1a\xd3\xab\x97>\xc3\xce?\x104\x06'),
        ),
    ]
