# Generated by Django 2.2.16 on 2021-03-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20210325_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'h$c\t`\xdf$\xf7$\xfdKd\\\x82\xc8\xe2T\x00\x00l\xd3rxl\xbe\xd7\x92\xe6\xe4\x1f\xb7\xd5'),
        ),
    ]
