# Generated by Django 2.2.16 on 2021-03-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20210325_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'\xd7\xd5WV\x83{\xf1Y\xdb\x16IG\x12\x8dF\xe1L&\x03\xd8\x82\xf6\xcev\x12N\x1c\x1d@\x91V\xd1'),
        ),
    ]
