# Generated by Django 2.2.16 on 2021-03-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20210325_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'\xfa\xb5\x1b\xcf\xbf_\xde\xc6%t&\xcfY\xa1\x97\xa7\xf2[\xc1\xf7d\xf6\x0e\xdb\xb4\xd1\x939\xd2_\xc9\x9c'),
        ),
    ]
