# Generated by Django 2.2.16 on 2021-03-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20210325_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'\xd8\x125\x80!\x8f\xf1\xce{\xa8MO\xa3\xe8\xb4#\x01\x88\xc1v\xc4\xf6\xf4\xdbmtu\x12\xb6z\x13\xc3'),
        ),
    ]
