# Generated by Django 2.2.16 on 2021-03-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_auto_20210328_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'\xb4\x84\xb4\x85\xce\xe19\xf0\xcc{\xe1\xa2\xf6o}u%A%F\xd2\x1ek\x1b>\x04\x80\xd7Z\xd9\xf5P'),
        ),
    ]
