# Generated by Django 2.2.16 on 2021-03-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_auto_20210328_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'\x98\xe1\x85\xa6&\x00\x88\xc1xt\x88"\r\xc8\x9b^Gm\xdd\x13\xcd\x10\xf7\x00K\xc4_\xf5\x8bw\xe8\xe2'),
        ),
    ]
