# Generated by Django 2.2.16 on 2021-03-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_auto_20210328_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'\xf2>\x04\x84P\xcd!\xcf\x82\xab\xbcm\x15\x13\xb6\xdf\xb4\x80oe\xa0\x97\xf5w&\xeb%\xf5\xea\xc4#\xf3'),
        ),
    ]
