# Generated by Django 2.2.16 on 2021-03-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_auto_20210328_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b"\x9a\xe4n\\6\xa0Va5\xc3\xa0\x87/(+\xcc\x999w\xa0\xdf\x00\x1d\xf22\x80\xec\xf5\x0c'.\xa6"),
        ),
    ]
