# Generated by Django 2.2.16 on 2021-03-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_auto_20210328_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'&\xd6\x9d\x12\xf1\xe7\xbc\x14\xa5\x15K\x1b\x1e\xff\xcf\xb6\x08pn\x0e7\xd513\xf5\n\x7f\xa29\xd1\xc5x'),
        ),
    ]
