# Generated by Django 2.2.16 on 2021-03-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_auto_20210328_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'\xe3\x903\x80^\xd5\x03\x07\x16\xc2c\xdd!\x9b\xfd5\xaax\x06\xc8\xfd?3\xff\x01\xb1=*6\x89\xf9\x1e'),
        ),
    ]
