# Generated by Django 2.2.16 on 2021-03-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_auto_20210328_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'\x1a\x19\xb7\xb97P\xc6\xb8\xdeF\xd1\xa9?\xbf\x11\xff\xf2\x12\x81\xdc\x07,x\x9a\x8f\xe8\xb1\x94cy}]'),
        ),
    ]
