# Generated by Django 2.2.16 on 2021-03-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_auto_20210328_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'\xaal\x94\xbdG\x1avm\x81A!P\xd5P/qh\xcb/@t\x8d\xc9\x82d\x9d\xd1\xe15(\xff\x1a'),
        ),
    ]
