# Generated by Django 2.2.16 on 2021-03-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_auto_20210328_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'DU\x9b\x9bj\xad3C\xb1\x00\xba\xb6\x9a\xbc\xd9-\x1d\xae\x02\xe7\x8c"y\xcf\'\xb0\xe3\x84@(\xba\x17'),
        ),
    ]
