# Generated by Django 2.2.16 on 2021-03-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_auto_20210328_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'\xa5\x9b\xcc\xbe\xb8I\xa2\xe4\xccc\x81\xc6\xca`N\xb1[\r\xbe\xe2\xff\xc3\xa8\xc9\xee\x9d:\x8d\xf5 P\xa9'),
        ),
    ]
