# Generated by Django 2.2.16 on 2021-03-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_auto_20210328_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'7\xef\xe3\x1c\xa6\x98\x19\xeb\x8co\x03\xa7\r\xb0`\x85=\rih\xfe\x90L\x91\xf3\x98\r\xb435\x0fR'),
        ),
    ]
