# Generated by Django 2.2.16 on 2021-03-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_auto_20210329_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'\xa0\x9b\xc6\xf5ii\x8b\x00\x98T\xbf\xcc\xcd|t\xb7\x05_\xf2\xcc\x8fcvei=_\x1f&\x12a_'),
        ),
    ]
