# Generated by Django 2.2.16 on 2021-03-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_auto_20210330_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'w\xacX\x15\xd7O\xed\xe8\xa5\xf5\x9e\x06\xc4\xa0x\x9fs\xa2?h\xb2\xd8\xac,\x18e\x91@P\x9e\xba\xec'),
        ),
    ]
