# Generated by Django 2.2.16 on 2021-03-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_auto_20210330_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'\xbbS\xf5\xfa\x7f\xd9-\xdba\xd2\xb1\x8fD"\xe0\xd7^d\xba\x0c%\x9dq$\xae\xc8\x1c\xa8\xe1\x8e\x8e\xc5'),
        ),
    ]
