# Generated by Django 2.2.16 on 2021-03-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_auto_20210330_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'\xc6\x97\xefj\xd2X\xff\xf7V\xf5\xf3Vw"2K\xb8u\xfa\xdf\t\xcc\xbaN\x1a^\x1c\x8a\x8b\x1d"\x8e'),
        ),
    ]
