# Generated by Django 2.2.16 on 2021-03-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_auto_20210330_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'\xb4qm\x05:\xf0\x0f\xce\xcapQ\x88\xcc\xe7\xbd\xb2\x89@o\xe4\x1b\x89\xf2\x0b!\xa10i\xf9\x95;u'),
        ),
    ]
