# Generated by Django 2.2.16 on 2021-03-30 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_auto_20210330_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'\xfc\xbb\xdbdq1=t\x0bc$a\xc6\x88.\xd2D\x86\xef\xe8\x806:e\xbcs\x81e\xce_;\x8e'),
        ),
    ]
