# Generated by Django 2.2.16 on 2021-03-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_auto_20210330_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'I\xc2i\xad\x18\x12\xc0\xe7>\xcc-%\xb1\x8f\'"\r\x0b\xa5\x11\x17\xe1q\x86\x98\xb8=A\xfc\x18\xfb\x0f'),
        ),
    ]
