# Generated by Django 2.2.16 on 2021-03-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_auto_20210330_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'\x7fo\x17\xab@sh\xfd\x1a\xa3\x96\x8d\xf0\xb8\xec\xae\x02\x1cwt^\xe8\x0c\xdc\x1e\xb4\xc0wj\xcc\xf1\xd3'),
        ),
    ]
