# Generated by Django 2.2.16 on 2021-03-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_auto_20210330_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'\x17\x1b\ta@sq\xee\x0eV\x88\xd6\xc7\xb7p\xeb:z\x9c\xe50d\xef\xb1"\xac\xc7G\xa51\xe6\xb9'),
        ),
    ]
