# Generated by Django 3.1.6 on 2021-04-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_auto_20210330_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'c\xc9\xbb\x88\xaeH\xe9\x86mU\xf31\xcc5\xb3\xdc\x8e^\x01>\xbd\xe1\xe0F\xc23\xe7&\xebnB\xf2'),
        ),
    ]
