# Generated by Django 3.1.6 on 2021-04-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_auto_20210408_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'\xc3\n/\t?~\x04K \xfd\n\x98\xb1LuD~NW\x90*\xdd\x8c\r\x13\xc88\xc6\x01\xff\x98d'),
        ),
    ]
