# Generated by Django 3.1.6 on 2021-04-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_auto_20210410_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'%\xf1\xe8\xba&\x12\x7f\x9d\x8e\x9e\xc9\x00\x06 .~\x8c\x98\x8c\xdf,\xf3\x12\x14\x7f>\x12\xe0,X\xe5*'),
        ),
    ]
