# Generated by Django 3.1.6 on 2021-04-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_auto_20210410_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'$\xf05XY\t\xbd\xc1\xed.X\x0fm\xc01\xdeBp\xfbC\xe9\x02\xeb\xaf\n~b\x85k\x03\xf1\x03'),
        ),
    ]
