# Generated by Django 3.1.6 on 2021-04-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_auto_20210410_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'r\xb2\xfd\x00\xa7\x06\xa1\xe58\xa4\x90Y\xb9`\x01\xa4\x8d\xfa\xbe\xf72\xe0~\xe0\xc5\xbc\x9b\xcbrWS\xf8'),
        ),
    ]
