# Generated by Django 3.1.6 on 2021-05-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_auto_20210410_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'\xc5p\xcbE\x83n\xa4\xf6\xfb\xca\x02QN\x00%a\xd4x\xe4\x89\xdd\xc3\xc4\xcf\xd4cP\x17L\xd6H\xa5'),
        ),
    ]
