# Generated by Django 3.1.6 on 2021-05-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0070_auto_20210508_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'i\xd1\xca\xb6\x8f\xbd\x83{k\xf9\x8e\x98QK+\n0\x88\xbck\x04\xb9C{\xf7bRKI\x7f\xf9\xc2'),
        ),
    ]
