# Generated by Django 3.1.6 on 2021-05-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0071_auto_20210508_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'\xb2[Gh\xe6\xdc\xbd\xbf\x9e\x8b\xf8\xd3\xfds\xdf\r\xb2\r)\xbc\xea\xfb/e\xbb\xe9\xab\xa2>G\xc6L'),
        ),
    ]
