# Generated by Django 3.1.6 on 2021-05-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0072_auto_20210508_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'c\xcf;\xf3\xd0#G\x84=f"A;\x87A\x17\xfc,\xd2$A\x91)\xa1\xf9\xe9\xde\xe5L;\xea\x85'),
        ),
    ]
