# Generated by Django 3.1.6 on 2021-05-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0073_auto_20210508_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'<O\x0eV\xf2\xc2\x9b\x03<<\x1e\x98\xa3\xb4s\x14#\xe4\xef:\xb0\x94]\xfd\xf2\x08\xdc0\xfa[\x91J'),
        ),
    ]
