# Generated by Django 3.1.6 on 2021-05-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0074_auto_20210508_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'\xe2g\x08eNb}\tL\xdfwa~\xe29\x11\xee\xb6\x19\n\xad\xb2_\xe3\xf4%\xb2\xd5v\x12*\x10'),
        ),
    ]
