# Generated by Django 3.1.6 on 2021-05-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0075_auto_20210508_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'\xa1vI\x88~\x93\\ ej\xbf\xfd\xd6\x84/\xe1\x80rq\xfb\xae93+Z\x94\xa3\xbb\xadnYc'),
        ),
    ]
