# Generated by Django 3.1.6 on 2021-05-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0076_auto_20210508_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'\xc5\x9a\xed\x9d-\xb5\x83\xb27\xd0X^.\x075\xc6\xcf\x834\xc2\x16\x91\x95\xb5~\x82\xda?*U\xb7\xe1'),
        ),
    ]
