# Generated by Django 3.1.6 on 2021-05-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0077_auto_20210509_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'4O\xce\xfa\xd9\xdb7ci\xd6\xda\x07\x06\x11BD\x85\x8a\xad\xca\xc22d\x98^s\xe2\x97\xb7\xaf\x07\xb9'),
        ),
    ]
