# Generated by Django 3.1.6 on 2021-05-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0078_auto_20210509_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'\xa3\xe1\x00\xe4\x05\x10\xa2L\xf8\x13\x8a+\xa0C\x86V\x8d\xeaaMO\x11\xf8kn\x9c\x97\xd4\xec\xf1\xcd\xd3'),
        ),
    ]
