# Generated by Django 3.1.6 on 2021-05-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0079_auto_20210509_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'2\xe44\xfaM"\xb8\xb6\xc7\x1d\x7f\x82Z\x15\x17}\xc6\x02\xb4\xa8\xff6O\x08\xe0\xf6\x8e\xc6\xd8<J\x00'),
        ),
    ]
