# Generated by Django 3.1.6 on 2021-05-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0080_auto_20210509_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'\n\xc5\x9f\xf5\\\xed\x86\xdc\xc6l\xfeH\xfd\x96\x93\xd8\xe2[\x95#N\xc4\xae\x07R1\x918<\x8b\x84D'),
        ),
    ]
