# Generated by Django 3.1.6 on 2021-05-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0081_auto_20210509_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'\x7f9\xfbXY\xe4Z\x8f\xb3\x90-\xea\xf3\xacy\x06D\x02J;L\xd9u\xb3\xf0 \xd6\x1c:q,\xed'),
        ),
    ]
