# Generated by Django 3.1.6 on 2021-05-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0083_auto_20210509_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivk',
            name='iv',
            field=models.TextField(default=b'\xeb\x16\xbcx\xa4o\x01V\xa3\xef+\xc6\xbc\x981\xa9w\x7f)\xdc\x15\x17u\x11]\xd8 :\xc7\xf41\xde'),
        ),
    ]
