# Generated by Django 3.1.6 on 2021-05-08 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('doc', models.FileField(upload_to='files')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('pin', models.CharField(blank=True, max_length=20, null=True)),
                ('thumbnail', models.ImageField(default='default.jpg', upload_to='')),
                ('encryption', models.CharField(choices=[('IVK & Pin', 'IVK & PIN'), ('IVK Only', 'IVK Only'), ('Pin Only', 'Pin Only'), ('None', 'None')], default=1, max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
