# Generated by Django 3.1.6 on 2021-05-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_delete_mygroupfiles'),
        ('fileshare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='belongsto',
            field=models.ManyToManyField(to='groups.MyGroup'),
        ),
    ]
