# Generated by Django 3.1.6 on 2021-05-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0002_files_belongsto'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='space',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='files',
            name='total_download_files',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='files',
            name='total_given_files',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='files',
            name='total_groups',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='files',
            name='total_owned_files',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='files',
            name='total_uploaded_files',
            field=models.IntegerField(default=0),
        ),
    ]
