# Generated by Django 3.1.6 on 2021-05-09 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0003_auto_20210509_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='space',
        ),
        migrations.RemoveField(
            model_name='files',
            name='total_download_files',
        ),
        migrations.RemoveField(
            model_name='files',
            name='total_given_files',
        ),
        migrations.RemoveField(
            model_name='files',
            name='total_groups',
        ),
        migrations.RemoveField(
            model_name='files',
            name='total_owned_files',
        ),
        migrations.RemoveField(
            model_name='files',
            name='total_uploaded_files',
        ),
    ]
